
import type { Artisan, Product } from './types';

export const artisans: Artisan[] = [
  {
    id: 'artisan-1',
    name: 'Lalita Devi',
    tradition: 'Madhubani Painting',
    location: 'Jitwarpur, Bihar',
    impact: 'Mentoring a new generation of female artists in her village to ensure the art form thrives.',
    story: 'Lalita Devi learned the intricate art of Madhubani painting from her mother and grandmother, a tradition passed down through generations of women in her family. Using brushes made from bamboo twigs and natural pigments from flowers and minerals, she creates vibrant depictions of mythology and daily life. Her work not only sustains her family but also empowers other women in her community to find financial independence through their shared cultural heritage.',
    avatarUrl: 'https://picsum.photos/seed/indian-woman-painting/200/200',
    avatarHint: 'woman madhubani painter',
  },
  {
    id: 'artisan-2',
    name: 'Ismail Khatri',
    tradition: 'Ajrakh Block Printing',
    location: 'Ajrakhpur, Gujarat',
    impact: 'Championing the use of natural dyes and sustainable practices in traditional block printing.',
    story: 'Ismail Khatri is a tenth-generation artisan of the famed Ajrakh block printing technique. For him, Ajrakh is a sacred tradition that involves a complex 16-step process of washing, dyeing, printing, and drying, all using natural dyes like indigo and madder. His family was instrumental in establishing Ajrakhpur, a village for artisans displaced by the 2001 earthquake, ensuring the survival of their community and craft.',
    avatarUrl: 'https://picsum.photos/seed/man-block-printing/200/200',
    avatarHint: 'man block printing',
  },
  {
    id: 'artisan-3',
    name: 'Anwar Chitrakar',
    tradition: 'Pattachitra Painting',
    location: 'Naya, West Bengal',
    impact: 'Reviving the tradition of Patua scroll painters who narrate stories through their art.',
    story: 'Anwar Chitrakar belongs to a unique community of Patuas, or scroll painters, who have practiced Pattachitra for centuries. His scrolls, painted with natural colors on stitched-together sheets of paper, depict mythological tales, social issues, and historical events. As he unfurls the scroll, he sings the "pater gaan"—a song that narrates the story painted on it, making his art a captivating performance.',
    avatarUrl: 'https://picsum.photos/seed/scroll-painter/200/200',
    avatarHint: 'man scroll painter',
  },
   {
    id: 'artisan-4',
    name: 'Bhuri Bai',
    tradition: 'Bhil Painting',
    location: 'Pitol, Madhya Pradesh',
    impact: 'One of the first Bhil artists to use paper and canvas, bringing her community\'s art to a global audience.',
    story: 'Bhuri Bai is a celebrated artist from the Bhil community. Growing up, she painted on the walls of her home, a common practice during festivals. Her work is characterized by vibrant dots and lines that form intricate patterns, depicting the myths, folklore, and daily life of her tribe. Her transition from village walls to canvas has been instrumental in preserving and popularizing Bhil art.',
    avatarUrl: 'https://picsum.photos/seed/tribal-woman/200/200',
    avatarHint: 'tribal woman painter',
  },
  {
    id: 'artisan-5',
    name: 'Ghulam Rasool',
    tradition: 'Kashmiri Paper Mache',
    location: 'Srinagar, Kashmir',
    impact: 'Sustaining a delicate, centuries-old craft that has been impacted by regional conflict.',
    story: 'In the heart of Srinagar, Ghulam Rasool delicately sands a paper mache box, preparing it for the intricate "naqqashi" painting. This craft, introduced to Kashmir from Persia in the 14th century, involves recycling waste paper into beautiful, lightweight artifacts. Despite challenges, he continues to create exquisite pieces, each hand-painted with motifs of chinar leaves and nightingales, a testament to Kashmir\'s enduring artistry.',
    avatarUrl: 'https://picsum.photos/seed/man-painting-box/200/200',
    avatarHint: 'man painting box',
  }
];

export const products: Product[] = [
  {
    id: 'prod-1',
    name: 'Tree of Life Madhubani Art',
    price: 95.0,
    material: 'Handmade Paper, Natural Dyes',
    origin: 'Jitwarpur, Bihar',
    description: 'A vibrant and intricate Madhubani painting of the Tree of Life, a symbol of growth and prosperity, filled with birds and fish.',
    imageUrl: 'https://picsum.photos/seed/madhubani-tree/600/600',
    imageHint: 'madhubani tree life',
    artisanId: 'artisan-1',
  },
  {
    id: 'prod-2',
    name: 'Indigo Ajrakh Stole',
    price: 75.0,
    material: 'Cotton, Natural Dyes',
    origin: 'Ajrakhpur, Gujarat',
    description: 'A beautiful cotton stole featuring traditional Ajrakh patterns, hand-block printed using natural indigo dyes.',
    imageUrl: 'https://picsum.photos/seed/indigo-shawl/600/600',
    imageHint: 'indigo block print',
    artisanId: 'artisan-2',
  },
  {
    id: 'prod-3',
    name: 'Ramayana Pattachitra Scroll',
    price: 180.0,
    material: 'Paper, Natural Pigments',
    origin: 'Naya, West Bengal',
    description: 'A detailed Pattachitra scroll painting narrating a scene from the epic Ramayana, using bold lines and natural colors.',
    imageUrl: 'https://picsum.photos/seed/pattachitra-ramayana/600/600',
    imageHint: 'pattachitra scroll',
    artisanId: 'artisan-3',
  },
  {
    id: 'prod-4',
    name: 'Bhil Celebration Painting',
    price: 120.0,
    material: 'Canvas, Acrylic Paint',
    origin: 'Pitol, Madhya Pradesh',
    description: 'A joyous Bhil painting alive with rhythmic dots and figures, depicting a tribal festival with dance and music.',
    imageUrl: 'https://picsum.photos/seed/bhil-festival/600/600',
    imageHint: 'bhil art painting',
    artisanId: 'artisan-4',
  },
  {
    id: 'prod-5',
    name: 'Kashmiri Paper Mache Box',
    price: 65.0,
    material: 'Paper pulp, Paint',
    origin: 'Srinagar, Kashmir',
    description: 'An elegant, hand-painted paper mache box, perfect for storing jewelry. Features fine floral "naqqashi" work.',
    imageUrl: 'https://picsum.photos/seed/kashmiri-box/600/600',
    imageHint: 'paper mache box',
    artisanId: 'artisan-5',
  },
  {
    id: 'prod-6',
    name: 'Fish Motif Madhubani Coasters',
    price: 35.0,
    material: 'Wood, Enamel Paint',
    origin: 'Jitwarpur, Bihar',
    description: 'Set of four wooden coasters, each hand-painted with the auspicious fish motif in the classic Madhubani style.',
    imageUrl: 'https://picsum.photos/seed/madhubani-fish/600/600',
    imageHint: 'madhubani coasters',
    artisanId: 'artisan-1',
  },
  {
    id: 'prod-7',
    name: 'Maroon Ajrakh Cotton Fabric',
    price: 85.0,
    material: 'Cotton, Madder Dye',
    origin: 'Ajrakhpur, Gujarat',
    description: 'Two meters of hand-block printed Ajrakh fabric, dyed with natural madder root for a rich maroon color.',
    imageUrl: 'https://picsum.photos/seed/maroon-fabric/600/600',
    imageHint: 'ajrakh fabric',
    artisanId: 'artisan-2',
  },
  {
    id: 'prod-8',
    name: 'Bhil Village Life Canvas',
    price: 150.0,
    material: 'Canvas, Acrylics',
    origin: 'Pitol, Madhya Pradesh',
    description: 'A large canvas painting by Bhuri Bai depicting the symbiotic relationship between her community and nature.',
    imageUrl: 'https://picsum.photos/seed/bhil-village/600/600',
    imageHint: 'tribal village art',
    artisanId: 'artisan-4',
  },
  {
    id: 'prod-9',
    name: 'Channapatna Wooden Toys',
    price: 40.0,
    material: 'Hale Mara Wood, Lacquer',
    origin: 'Channapatna, Karnataka',
    description: 'A set of three eco-friendly, traditional Channapatna wooden toys, colored with natural, non-toxic lacquer.',
    imageUrl: 'https://picsum.photos/seed/wooden-toys-india/600/600',
    imageHint: 'wooden toys',
    artisanId: 'artisan-x', // To show a product without a linked artisan
  },
  {
    id: 'prod-10',
    name: 'Srikalahasti Kalamkari Painting',
    price: 250.0,
    material: 'Cotton Canvas, Natural Dyes',
    origin: 'Srikalahasti, Andhra Pradesh',
    description: 'An intricate, free-hand "kalam" (pen) drawing depicting a scene from Mahabharata, using only natural dyes.',
    imageUrl: 'https://picsum.photos/seed/kalamkari-mahabharata/600/600',
    imageHint: 'kalamkari painting',
    artisanId: 'artisan-x',
  },
  {
    id: 'prod-11',
    name: 'Dhokra Nandi Bull',
    price: 65.0,
    material: 'Brass',
    origin: 'Bastar, Chhattisgarh',
    description: 'A unique Dhokra metal-casted statue of the Nandi bull, created using the ancient lost-wax casting technique. Note: The artisan for this is not in the list, so it will not have an artisan link.',
    imageUrl: 'https://picsum.photos/seed/dhokra-bull/600/600',
    imageHint: 'brass statue',
    artisanId: 'artisan-x',
  },
  {
    id: 'prod-12',
    name: 'Jaipur Blue Pottery Mug Set',
    price: 50.0,
    material: 'Ceramic, Quartz Powder',
    origin: 'Jaipur, Rajasthan',
    description: 'A set of two hand-painted mugs in the iconic Jaipur Blue Pottery style, featuring a delicate leaf motif. No lead or cadmium.',
    imageUrl: 'https://picsum.photos/seed/blue-pottery-mugs/600/600',
    imageHint: 'blue pottery mugs',
    artisanId: 'artisan-x',
  }
];
